name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai_code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r AutoSyntaxReviewer/requirements.txt 

      
      - name: Run Unit Tests and Generate Report
        run: |
          pip install pytest
          cd AutoSyntaxReviewer
          pytest test_example.py --junitxml=result.xml || true  # Continue even if tests fail

      - name: Parse Test Results
        run: |
          cd AutoSyntaxReviewer
          python parse_test_results.py result.xml

      - name: Run Tests with Coverage
        run: |
          pip install coverage
          cd AutoSyntaxReviewer
          coverage run -m pytest test_example.py --junitxml=result.xml || true
          coverage report > coverage.txt

      - name: Parse Code Coverage
        run: |
          cd AutoSyntaxReviewer
          python parse_coverage.py coverage.txt

      - name: Export Coverage Summary
        id: coverage-summary
        run: |
          cd AutoSyntaxReviewer
          COVERAGE=$(cat coverage_summary.txt)
          echo "coverage=$COVERAGE" >> $GITHUB_ENV


      - name: Run AI code review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          cd AutoSyntaxReviewer
          python ai_review.py "${{ github.event.pull_request.number }}"

      - name: Export Test Summary
        id: test-summary
        run: |
          cd AutoSyntaxReviewer
          SUMMARY=$(cat test_summary.txt)
          echo "summary=$SUMMARY" >> $GITHUB_ENV


